pipeline {
    agent any
    
    stages {
      stage ("Deploying to Development server") {
        	steps {
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "sudo docker-compose -f reactjs-dev-docker-compose.yml down"'
            	sh 'scp docker/dev/deploy.sh docker/dev/reactjs-dev-docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~/'
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "chmod +x deploy.sh reactjs-dev-docker-compose.yml"'
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "./deploy.sh"'
          }
          
      }
    }
}
