pipeline {
    agent any
    
    stages {
      stage ("Deploying to Development server") {
        	steps {
                sshagent(['my-ssh-key']) {
                    sh """
                        ssh ${REMOTE_USER}@${REMOTE_HOST} 'ls'
                    """
                }
            	
          }
      }
    }
}
