pipeline {
    agent any
    
    stages {
      stage ("Deploying to Production server") {
        	steps {
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "sudo docker-compose -f reactjs-prod-docker-compose.yml down"'
            	sh 'scp docker/prod/deploy.sh docker/prod/reactjs-prod-docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~/'
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "chmod +x deploy.sh reactjs-prod-docker-compose.yml"'
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "./deploy.sh"'
          }
          post {
              success {
                  input message: 'Do you want to Deploy application in Production environment? (Click "Proceed" to continue)'
                  build job: 'Deploy_reactjs_app_to_Prod_env' , wait: false
                  
                  //emailext body: 'Job master successful', subject: 'Job Success', to: 'girish.b.m4567@gmail.com' , attachLog: false
        
      
                  }
              }
      }
    }
}
