pipeline {
    agent any
    
    stages {
      stage ("Deploying to Production server") {
        	steps {
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "sudo docker-compose -f reactjs-prod-docker-compose.yml down"'
            	sh 'scp docker/prod/deploy.sh docker/prod/reactjs-prod-docker-compose.yml ${REMOTE_USER}@${REMOTE_HOST}:~/'
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "chmod +x deploy.sh reactjs-prod-docker-compose.yml"'
                sh 'ssh ${REMOTE_USER}@${REMOTE_HOST} "./deploy.sh"'
                echo "Application Deployed on Production server and check using url: http://${REMOTE_HOST}:80"
          }
          
      }
    }
}
